config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" 
  resources :users, only: [:new, :create, :show, :edit, :update, :index]
  resources :sessions, only: [:new, :create, :destroy]
  resources :favorites, only:[:create, :destroy, :index]
  resources :pictures do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence:true
  validates :image, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pictures, dependent: :destroy
  has_many :favorites, dependent: :destroy
  mount_uploader :image, ImageUploader
  before_validation { email.downcase! }
  has_secure_password
  
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  validates :name,  presence: true,
                                    length: { maximum: 30 }
  validates :email, presence: true, 
                                    length: { maximum: 255 },
                                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                                    uniqueness: {case_sensitive: false}                                    
                          
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  private
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "ログインしてください"
      redirect_to new_session_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
    @favorites = current_user.favorites
  end

  def new
    @favorite = Favorite.new
  end

  def create
    @favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_url, notice: "#{@favorite.picture.user.name}さんのお気に入り登録をしました"
  end

  def destroy
    @favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_url, notice: "#{@favorite.picture.user.name}さんのお気に入りを解除しました"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
 
  def home
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :logged_in_user, only:[:new,:create,:destroy, :edit, :update]
  def index
    @pictures = Picture.all
  end

  def new
    if params[:back]
      @picture = current_user.pictures.new(picture_params)
    else
    @picture = current_user.pictures.new
    end
  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def update
    @picture = Picture.find(params[:id])
    if @picture.update(picture_params)
    redirect_to pictures_path, notice:"画像を編集しました"
    else
      render 'edit'
    end
  end

  def confirm
    @picture = current_user.pictures.new(picture_params)
     if @picture.invalid?
      render 'new'
    end
  end


  def create
    @picture = current_user.pictures.build(picture_params)
    if @picture.save
      PictureMailer.picture_mail(@picture).deliver
      flash[:success] = "Pictureを投稿しました！"
      redirect_to pictures_path
    else
      render 'new'
    end
  end

  def show
    @picture = Picture.find(params[:id])
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    flash[:danger] = "投稿が削除されました！"
    redirect_to pictures_path
  end
  
  private
  def picture_params
    params.require(:picture).permit(:content, :image, :image_cache)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました。'
    render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :index]
  before_action :correct_user, only:[:edit, :update]

  def new
    @user = User.new
  end

  def create 
    @user = User.new(user_params) 
    if @user.save
      log_in @user
      flash[:success] = "Welcome to インスタ clone!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit 
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "プロフィールを更新しました！"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    @users = User.all
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :image, :password,
      :password_confirmation)
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in"
      redirect_to new_session_url
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url user
    return user.image if user.image
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "https://www.gravatar.com/avatar/#{gravatar_id}.jpg"
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    current_user.present?
  end 
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/favorites/index.html.erb
<% provide(:title, "favorite page")%>
<h1>お気に入り一覧</h1>
<div class="row">
  <div class="col-md-8">
    <div class="card-favorite">
      <% @favorites.each do |favorite| %>
        <%= image_tag favorite.picture.image.thumb.url,class:"favorite-img" %>  
        <div class="card-body">
          <p class="card-title">User name:  <%= favorite.user.name %></p>
          <p class="card-text">Picture 内容<br><%= favorite.picture.content %></p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IGClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  </head>
  <body>
  <header class="navbar navbar-expand-lg navbar-light bg-warning">
      <div class="container">
        <div class="home-logo">
          <%= link_to image_tag("instaclone.png",alt:"insta logo") , "#", id: "logo" %>
        </div>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
              <li><%= link_to "ユーザーの一覧", users_path %></li>
              <li><%= link_to "写真を投稿", new_picture_path, class: 'btn btn-primary btn-lg' %> </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  アカウント設定 <b class = "caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "プロフィール", user_path(current_user.id) %> </li>
                  <li><%= link_to "ユーザー設定", edit_user_path(current_user) %> </li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "ログアウトする", session_path(current_user.id), method: :delete %>
                  </li>
                </ul>
              </li>
              <% else %>
                <li><%= link_to "ログイン", new_session_path %></li>
              <% end %>
              </ul>
            </li>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1 class="mt-5">Welcome to Insta Clone</h1>
<p class="lead">下のボタンでユーザー登録をして下さい</p>
<div class="sign-up-botton">
  <%= link_to "Sign up", new_user_path, class: "btn btn-success btn-lg" %>
</div>
<h5>既にメンバーの方はこちらから<%= link_to "ログイン", new_session_path %> をして下さい</h5>

app/views/pictures/confirm.html.erb
<h3>投稿の確認</h3>
<div class="row">
  <div class="col-md-6  col-md-offset-3">
    <%= form_with(model:@picture, local: true) do |f| %>
      <%= image_tag(@picture.image.thumb.url,class:"confirm_image")if @picture.image_url %>
      
      <%= f.hidden_field :image_cache %>
      <%= f.hidden_field :content %>
      
      <%= f.submit "投稿", class: 'btn btn-primary'%>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-6  col-md-offset-3">
    <%= form_with(model:@picture, url: new_picture_path, local:true, method: "get") do |f| %>
      <%= f.hidden_field :image_cache %>
      
      <%= f.submit "戻る", name: "back", class: 'btn btn-danger'%>
    <% end %>
  </div>
</div>

app/views/pictures/edit.html.erb
<h1>投稿を編集する</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_with(model: @picture, local: true) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :content %>
        <%= f.text_area :content, placeholder: "投稿内容の編集", class: 'form-control' %>

        <%= f.label :image %>
        <%= f.file_field :image, class: 'form-control'%>
        
        <%= f.submit "投稿する", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
  

app/views/pictures/index.html.erb
<div class="card">
  <div class="col-md-8">
    <% @pictures.each do |picture| %>
      <div class="card-wrap">
      <div class="card-picture-index">
        <div class="card-header align-items-center d-flex">
          <%= image_tag picture.image.thumb.url %>
          <%= link_to user_path(picture.user), class: "no-text-decoration" do %> <br>
          <% if picture.user.image?%>
          <%= image_tag picture.user.image.thumb50.url , class:"picture-profile-icon" %>
          <% else %>
            <%= image_tag 'instauser.png',  size: '100×100', class: "picture-profile-icon"%>
          <% end %>  
          <% end %>
          <%= link_to user_path(picture.user), class:"black-color no-text-decoration", title: picture.user.name do %>
          <strong><%= picture.user.name%> </strong>
          <%= link_to "投稿詳細", picture_path(picture.id), class:"btn btn-success" %>
          <% if picture.user_id == current_user.id %>
          <%= link_to "削除", picture_path(picture.id), method: :delete, 
          class: 'btn btn-danger',data: {confirm:"本当に削除しますか?"} %>
          <% end %>                                                      
          <% end %>
        </div>
        <% end %>  
      </div>
    </div>
  </div>   
</div>

app/views/pictures/new.html.erb
<h1>新しく投稿する</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @picture, local: true, url: choose_new_or_edit) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      
      <%= f.label :content %>
      <%= f.text_area :content, placeholder: "新規投稿...", class: 'form-control' %>

      <%= f.label :image %>
      <%= f.file_field :image, class: 'form-control'%>
      
      <%= f.submit "投稿する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/pictures/show.html.erb
<%= image_tag @picture.image.medium.url, class:"show-picture" %>
<div class="card-body">
  <%= link_to "戻る", pictures_path, class: 'btn btn-default'%>
  <% if @picture.user_id == current_user.id %>
  <%= link_to "投稿の更新", edit_picture_path(@picture.id), class:'btn btn-warning'%>
  <% end %>
  <hr>
  <div class="row parts">
    <% unless @picture.user_id == current_user.id %>
      <% if @favorite.present? %>
      <%= link_to 'お気に入りを解除する', favorite_path(id: @favorite.id), method: :delete, class:'btn btn-danger'%>
      <% else %>
      <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class:'btn btn-success'%>
      <% end %>
    <% end %>
    <div>
      <span>投稿者:<strong><%= @picture.user.name %></strong></span><br>
      <span>投稿内容:<strong><%= @picture.content %></strong></span>
      <%= link_to time_ago_in_words(@picture.created_at).upcase + "前","#",class:"post-time no-test-decoration" %>
      <form action="#" class="w-100">
      <div><textarea class="form-control comment-input border-0" placeholder="コメント..."rows="5"></textarea></div>
      </form>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
       <%= t('.errors count', errors_count: object.errors.count) %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>ユーザー情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages',object:f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.label :image %>
      <%= f.file_field :image %>

      <%= f.submit t('.Save changes'), class: "btn btn-primary" %>
    <% end %>

    

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>ユーザーの一覧</h1>
  <ul class="users">
    <% @users.each do |user| %>
      <li>
        <%= image_tag user.image.url if user.image.present? %>
        <%= link_to user.name, user %>
      </li>
    <% end %>
  </ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up' ) %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local:true) do |f| %>
    <%= render 'shared/error_messages', object:f.object %>
    
    <%= f.label :name %>
    <%= f.text_field :name, class:"form-control" %>

    <%= f.label :email %>
    <%= f.email_field :email, class:"form-control" %>

    <%= f.label :password %>
    <%= f.password_field :password, class:"form-control" %>
    
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class:"form-control" %>
    
    <%= f.label :image %>
    <%= f.file_field :image %>

    <%= f.submit t('.Create my account'), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="profile-wrap">
  <div class="row">
    <div class="col-md-10">
      <% provide(:title, @user.name) %>
      <h1>
        <% if @user.image? %>
          <%= image_tag @user.image.thumb50.url, class:"user-profile-icon" %>
        <% else %>
          <%= image_tag 'instauser.png', size: '100x100' %>
        <% end %>
        <%= @user.name %> 
        <%= link_to "投稿一覧", pictures_path, class: 'btn btn-success btn-lg' if @user.pictures.any? %>
        <%= link_to "お気に入り一覧", favorites_path, class: 'btn btn-warning btn-lg' if @user.favorites.any? %>
      </h1>
    </div>
  </div>
</div>